parameters:
#    fly.example.class: Nahakiole\FlyBundle\Example

services:
  acme_your_bundle.name_of_your_form.form.type:
    class: Nahakiole\FlyBundle\Form\PacketType
    arguments:
      entityManager: "@doctrine"